from dotenv import load_dotenv
import os
load_dotenv(verbose=True)

# explorer
JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN = str(os.getenv("JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN"))
JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT = str(os.getenv("JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT"))
EXPLORER_URL = "http://" + JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN + ":" + JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT + "/"

# this node wallet
THIS_NODE_WALLET = str(os.getenv("THIS_NODE_WALLET"))
THIS_NODE_WIF = str(os.getenv("THIS_NODE_WIF"))
THIS_NODE_PUBKEY = str(os.getenv("THIS_NODE_PUBKEY"))

# rpc
RPC_USER = str(os.getenv("KOMODO_SMARTCHAIN_NODE_USERNAME"))
RPC_PASSWORD = str(os.getenv("KOMODO_SMARTCHAIN_NODE_PASSWORD"))
RPC_PORT = str(os.getenv("KOMODO_SMARTCHAIN_NODE_RPC_PORT"))
KOMODO_NODE = str(os.getenv("KOMODO_SMARTCHAIN_NODE_IPV4_ADDR"))

# test wallets
TEST_THIS_NODE_WALLET = str(os.getenv("TEST_THIS_NODE_WALLET"))
TEST_THIS_NODE_WIF = str(os.getenv("TEST_THIS_NODE_WIF"))
TEST_GEN_WALLET_PASSPHRASE = str(os.getenv("TEST_GEN_WALLET_PASSPHRASE"))
TEST_GEN_WALLET_PUBKEY = str(os.getenv("TEST_GEN_WALLET_PUBKEY"))
TEST_GEN_WALLET_WIF = str(os.getenv("TEST_GEN_WALLET_WIF"))
TEST_GEN_WALLET_ADDRESS = str(os.getenv("TEST_GEN_WALLET_ADDRESS"))

# import api
IMPORT_API_HOST = str(os.getenv("IMPORT_API_HOST"))
IMPORT_API_PORT = str(os.getenv("IMPORT_API_PORT"))
IMPORT_API_BASE_URL = "http://" + IMPORT_API_HOST + ":" + IMPORT_API_PORT + "/"
