from dotenv import load_dotenv
import os
load_dotenv(verbose=True)

JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN = str(os.getenv("JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN"))
JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT = str(os.getenv("JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT"))
EXPLORER_URL = "http://" + JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN + ":" + JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT + "/"
THIS_NODE_WALLET = str(os.getenv("THIS_NODE_WALLET"))
THIS_NODE_WIF = str(os.getenv("THIS_NODE_WIF"))
RPC_USER = str(os.getenv("IJUICE_KOMODO_NODE_USERNAME"))
RPC_PASSWORD = str(os.getenv("IJUICE_KOMODO_NODE_PASSWORD"))
RPC_PORT = str(os.getenv("IJUICE_KOMODO_NODE_RPC_PORT"))
KOMODO_NODE = str(os.getenv("IJUICE_KOMODO_NODE_IPV4_ADDR"))
