from dotenv import load_dotenv
import os
load_dotenv(verbose=True)

IJUICE_WORKAROUND_LOCATION_NODE_IPV4_ADDR = str(os.getenv("IJUICE_WORKAROUND_LOCATION_NODE_IPV4_ADDR"))
IJUICE_WORKAROUND_LOCATION_NODE_USERNAME = str(os.getenv("IJUICE_WORKAROUND_LOCATION_NODE_USERNAME"))
IJUICE_WORKAROUND_LOCATION_NODE_PASSWORD = str(os.getenv("IJUICE_WORKAROUND_LOCATION_NODE_PASSWORD"))
WORKAROUND_LOCATION_NODE_WIF = str(os.getenv("WORKAROUND_LOCATION_NODE_WIF"))
WORKAROUND_LOCATION_NODE_WALLET = str(os.getenv("WORKAROUND_LOCATION_NODE_WALLET"))
WORKAROUND_LOCATION_NODE_PUBKEY = str(os.getenv("WORKAROUND_LOCATION_NODE_PUBKEY"))
IJUICE_WORKAROUND_CERTIFICATES_NODE_IPV4_ADDR = str(os.getenv("IJUICE_WORKAROUND_CERTIFICATES_NODE_IPV4_ADDR"))
IJUICE_WORKAROUND_CERTIFICATES_NODE_USERNAME = str(os.getenv("IJUICE_WORKAROUND_CERTIFICATES_NODE_USERNAME"))
IJUICE_WORKAROUND_CERTIFICATES_NODE_PASSWORD = str(os.getenv("IJUICE_WORKAROUND_CERTIFICATES_NODE_PASSWORD"))
WORKAROUND_CERTIFICATES_NODE_WIF = str(os.getenv("WORKAROUND_CERTIFICATES_NODE_WIF"))
WORKAROUND_CERTIFICATES_NODE_WALLET = str(os.getenv("WORKAROUND_CERTIFICATES_NODE_WALLET"))
WORKAROUND_CERTIFICATES_NODE_PUBKEY = str(os.getenv("WORKAROUND_CERTIFICATES_NODE_PUBKEY"))
