from dotenv import load_dotenv
import os
load_dotenv(verbose=True)

MULTI_1X = 1
MULTI_2X = 2
MULTI_3X = 3
MULTI_4X = 4
MULTI_5X = 5

# explorer
JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN = str(os.getenv("JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_HOST"))
JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT = str(os.getenv("JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT"))
EXPLORER_URL = "http://" + JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN + ":" + JUICYCHAIN_EXPLORER_MAINNET_UNCHAIN_PORT + "/"

# this node wallet
THIS_NODE_WALLET = str(os.getenv("THIS_NODE_WALLET"))
THIS_NODE_RADDRESS = str(os.getenv("THIS_NODE_RADDRESS"))
THIS_NODE_WIF = str(os.getenv("THIS_NODE_WIF"))
THIS_NODE_PUBKEY = str(os.getenv("THIS_NODE_PUBKEY"))

# rpc
# RPC_USER = str(os.getenv("KOMODO_SMARTCHAIN_NODE_USERNAME"))
# RPC_PASSWORD = str(os.getenv("KOMODO_SMARTCHAIN_NODE_PASSWORD"))
# RPC_PORT = str(os.getenv("KOMODO_SMARTCHAIN_NODE_RPC_PORT"))
# KOMODO_NODE = str(os.getenv("KOMODO_SMARTCHAIN_NODE_IPV4_ADDR"))
RPC_USER = str(os.getenv("KOMODO_SMARTCHAIN_NODE_USERNAME"))
RPC_PASSWORD = str(os.getenv("KOMODO_SMARTCHAIN_NODE_PASSWORD"))
RPC_PORT = str(os.getenv("KOMODO_SMARTCHAIN_NODE_RPC_PORT"))
KOMODO_NODE = str(os.getenv("KOMODO_SMARTCHAIN_NODE_IPV4_ADDR"))

# test wallet
TEST_GEN_WALLET_PASSPHRASE = "testing123"
TEST_GEN_WALLET_PUBKEY = "035b955ecee91343cae751b6b5c5c1b0efbd3a24ff0a622d8782e11b43eb8ec5af"
TEST_GEN_WALLET_WIF = "UriaaZ1hEftNZFM8pw9TXLF3iMqn2usCJDqeSnfAVkaPEwZXstLK"
TEST_GEN_WALLET_RADDRESS = "RDLtn5usEfoukyL2XqbcuoAg1sohU3m1F1"

# import api
IMPORT_API_HOST = str(os.getenv("IMPORT_API_HOST"))
IMPORT_API_PORT = str(os.getenv("IMPORT_API_PORT"))
IMPORT_API_BASE_URL = "http://" + IMPORT_API_HOST + ":" + IMPORT_API_PORT + "/"

# tweakable changes
BLOCKNOTIFY_CHAINSYNC_LIMIT = 5
HOUSEKEEPING_RADDRESS = "RS7y4zjQtcNv7inZowb8M6bH3ytS1moj9A"

# integrity/
DEV_IMPORT_API_JCF_BATCH_INTEGRITY_PATH = "integrity/"
# batch/require_integrity/
DEV_IMPORT_API_JCF_BATCH_REQUIRE_INTEGRITY_PATH = "batch/require_integrity/"
# raw/refresco/require_integrity/
DEV_IMPORT_API_RAW_REFRESCO_REQUIRE_INTEGRITY_PATH = "raw/refresco/require_integrity/"
# raw/refresco-integrity/
DEV_IMPORT_API_RAW_REFRESCO_INTEGRITY_PATH = "raw/refresco-integrity/"
# raw/refresco-tstx/
DEV_IMPORT_API_RAW_REFRESCO_TSTX_PATH = "raw/refresco-tstx/"
# raw/refresco/
DEV_IMPORT_API_RAW_REFRESCO_PATH = "raw/refresco/"

# LOAD JUICYCHAIN ENV
JUICYCHAIN_API_HOST = str(os.getenv("JUICYCHAIN_API_HOST"))
JUICYCHAIN_API_PORT = str(os.getenv("JUICYCHAIN_API_PORT"))
JUICYCHAIN_API_VERSION_PATH = str(os.getenv("JUICYCHAIN_API_VERSION_PATH"))
JUICYCHAIN_API_BASE_URL = "http://" + JUICYCHAIN_API_HOST + \
    ":" + JUICYCHAIN_API_PORT + "/" + JUICYCHAIN_API_VERSION_PATH

JUICYCHAIN_API_ORGANIZATION_CERTIFICATE_NORADDRESS = "certificate/noraddress/"
JUICYCHAIN_API_ORGANIZATION_CERTIFICATE = "certificate/"
# TODO unused
JUICYCHAIN_API_ORGANIZATION_CERTIFICATE_RULE = "certificate-rule/noraddress/"
JUICYCHAIN_API_ORGANIZATION_BATCH = "batch/"
JUICYCHAIN_API_ORGANIZATION = "organization/"

# FUNDING
FUNDING_AMOUNT_CERTIFICATE = 5
FUNDING_UTXO_COUNT_CERTIFICATE = 10
FUNDING_AMOUNT_LOCATION = 5
FUNDING_UTXO_COUNT_LOCATION = 10
FUNDING_AMOUNT_TIMESTAMPING_START = 0.091
FUNDING_AMOUNT_TIMESTAMPING_END = 0.092
